export const ALL_CATEGORIES = [
  'Piso',
  'Rodapé',
  'Parede',
  'Azulejo/Revestimento',
  'Bancada',
  'Armários',
  'Pia',
  'Cuba/Pia',
  'Torneira',
  'Torneira/Misturador',
  'Fogão',
  'Forno',
  'Micro-ondas',
  'Geladeira',
  'Lava-louças',
  'Exaustor/Coifa',
  'Iluminação',
  'Tomadas/Interruptores',
  'Lixeira',
  'Sofá',
  'Mesa de Centro',
  'Rack/Painel TV',
  'TV',
  'Cortina/Persiana',
  'Ar-condicionado',
  'Tapete',
  'Quadros/Decoração',
  'Cama/Cabeceira',
  'Colchão',
  'Guarda-roupa',
  'Criado-mudo',
  'Ventilador/Ar-condicionado',
  'Espelho',
  'Vaso Sanitário',
  'Chuveiro/Ducha',
  'Banheira',
  'Box/Divisória',
  'Acessórios',
  'Exaustor',
  'Máquina de Lavar',
  'Secadora',
  'Tanque',
  'Armário/Prateleira',
  'Varal',
  'Portão',
  'Prateleiras/Armário',
  'Móveis',
  'Churrasqueira',
  'Cortina/Toldo',
  'Plantas/Vasos',
  'Mesa',
  'Cadeira',
  'Estante/Prateleira',
] as const;

export type Category = (typeof ALL_CATEGORIES)[number];
