export interface DefaultRoom {
  name: string;
  icon: string;
  color: string;
  categories: string[];
}

export const DEFAULT_ROOMS: DefaultRoom[] = [
  {
    name: 'Sala',
    icon: 'tv',
    color: '#C1694F',
    categories: [
      'Piso',
      'Rodapé',
      'Parede',
      'Sofá',
      'Mesa de Centro',
      'Rack/Painel TV',
      'TV',
      'Iluminação',
      'Cortina/Persiana',
      'Ar-condicionado',
      'Tapete',
      'Quadros/Decoração',
      'Tomadas/Interruptores',
    ],
  },
  {
    name: 'Cozinha',
    icon: 'coffee',
    color: '#A85740',
    categories: [
      'Piso',
      'Azulejo/Revestimento',
      'Bancada',
      'Armários',
      'Pia',
      'Torneira',
      'Fogão',
      'Forno',
      'Micro-ondas',
      'Geladeira',
      'Lava-louças',
      'Exaustor/Coifa',
      'Iluminação',
      'Tomadas/Interruptores',
      'Lixeira',
    ],
  },
  {
    name: 'Quarto Principal',
    icon: 'moon',
    color: '#5B7553',
    categories: [
      'Piso',
      'Rodapé',
      'Parede',
      'Cama/Cabeceira',
      'Colchão',
      'Guarda-roupa',
      'Criado-mudo',
      'Iluminação',
      'Ventilador/Ar-condicionado',
      'Cortina/Persiana',
      'Tomadas/Interruptores',
      'Espelho',
    ],
  },
  {
    name: 'Quarto 2',
    icon: 'moon',
    color: '#6F9366',
    categories: [
      'Piso',
      'Rodapé',
      'Parede',
      'Cama/Cabeceira',
      'Colchão',
      'Guarda-roupa',
      'Criado-mudo',
      'Iluminação',
      'Ventilador/Ar-condicionado',
      'Cortina/Persiana',
      'Tomadas/Interruptores',
    ],
  },
  {
    name: 'Quarto 3',
    icon: 'moon',
    color: '#8FAD88',
    categories: [
      'Piso',
      'Rodapé',
      'Parede',
      'Cama/Cabeceira',
      'Colchão',
      'Guarda-roupa',
      'Criado-mudo',
      'Iluminação',
      'Ventilador/Ar-condicionado',
      'Cortina/Persiana',
      'Tomadas/Interruptores',
    ],
  },
  {
    name: 'Banheiro Social',
    icon: 'droplet',
    color: '#3B82F6',
    categories: [
      'Piso',
      'Azulejo/Revestimento',
      'Vaso Sanitário',
      'Cuba/Pia',
      'Torneira/Misturador',
      'Chuveiro/Ducha',
      'Box/Divisória',
      'Espelho',
      'Armário',
      'Acessórios',
      'Iluminação',
      'Exaustor',
    ],
  },
  {
    name: 'Banheiro Suíte',
    icon: 'droplet',
    color: '#6366F1',
    categories: [
      'Piso',
      'Azulejo/Revestimento',
      'Vaso Sanitário',
      'Cuba/Pia',
      'Torneira/Misturador',
      'Chuveiro/Ducha',
      'Banheira',
      'Box/Divisória',
      'Espelho',
      'Armário',
      'Acessórios',
      'Iluminação',
      'Exaustor',
    ],
  },
  {
    name: 'Área de Serviço',
    icon: 'wind',
    color: '#8B5CF6',
    categories: [
      'Piso',
      'Azulejo/Revestimento',
      'Máquina de Lavar',
      'Secadora',
      'Tanque',
      'Torneira',
      'Armário/Prateleira',
      'Varal',
      'Iluminação',
      'Tomadas/Interruptores',
    ],
  },
  {
    name: 'Garagem',
    icon: 'truck',
    color: '#6B7280',
    categories: [
      'Piso',
      'Portão',
      'Iluminação',
      'Tomadas/Interruptores',
      'Prateleiras/Armário',
    ],
  },
  {
    name: 'Varanda',
    icon: 'sun',
    color: '#F59E0B',
    categories: [
      'Piso',
      'Revestimento',
      'Móveis',
      'Iluminação',
      'Churrasqueira',
      'Pia/Bancada',
      'Cortina/Toldo',
      'Plantas/Vasos',
      'Tomadas/Interruptores',
    ],
  },
  {
    name: 'Corredor',
    icon: 'arrow-right',
    color: '#A89270',
    categories: ['Piso', 'Rodapé', 'Parede', 'Iluminação', 'Quadros/Decoração'],
  },
  {
    name: 'Escritório',
    icon: 'monitor',
    color: '#0EA5E9',
    categories: [
      'Piso',
      'Rodapé',
      'Parede',
      'Mesa',
      'Cadeira',
      'Estante/Prateleira',
      'Iluminação',
      'Ar-condicionado',
      'Cortina/Persiana',
      'Tomadas/Interruptores',
    ],
  },
];
